### ISSUE TITLE
XMC-2 Failed to Set Up

### ISSUE THREAD

**Issue by JoshMcWilson** [peteS-UK/emotiva#1]
Trying to add an XMC-2 with this integration, but get an error each time I try to go through the configuration process. 

![image](https://github.com/peteS-UK/emotiva/assets/21319917/07b87bf8-caa6-4dab-83ea-99dce394dc97)

I added the integration through HACS, restarted HA, added the custom integration, restarted HA, and then attempted to add the XMC-2. I get a success message after searching for the XMC-2, but then get that error. Here is the only thing in the logs I can find:

`Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 1:19:28 AM (4 occurrences)
Last logged: 1:25:28 AM

Error setting up entry Emotiva Processor for emotiva
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emotiva/__init__.py", line 61, in async_setup_entry
    _update_extra_notifications(emotiva,entry.options[CONF_NOTIFICATIONS])
                                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'notifications'`

**Comment by JoshMcWilson** [comment]
Ah, tried installing version 1.6 instead of the latest (1.61) and it worked! Would still be happy to help test if it would be helpful in regards to why that version is failing for me.

**Comment by peteS-UK** [comment]
Hi Josh.  Fixed that one already I think, but need to push a new version.  For now, go into the failed entry and select configure

![image](https://github.com/peteS-UK/emotiva/assets/64092177/fb284402-3d98-4b68-9c71-49c6b3428ff2)

Add a notification to track (e.g. back), then reload and the entities will be created correctly.  Let me know if that works, and I'll push the fix.

**Comment by JoshMcWilson** [comment]
That fixed it! Updated to 1.61, followed your instructions, and it fixed the integration. Thanks for the reply! Let me know if you would like me to test the updated version when it's available.

**Comment by peteS-UK** [comment]
OK - fixed in 1.62.  Pull the new update from HACS and let me know if it works.  BTW, I'd also be interested in the list of sound modes in XMC-2.  They're different to XMC-1 and I need the internal names.  If this fix works, open a new issue for "incorrect sound modes in xmc-2" and we'll sort that out.  Right now, you'll see the sound modes for xmc-1 only.

**Comment by JoshMcWilson** [comment]
Seems like it's working, I tried to go into Configure and remove that notification I had set up but doesn't seem to take when I try to remove it. Not sure if that's intended or not.

I'll try and get you the sound modes tomorrow if I have a chance. Thanks!

**Comment by peteS-UK** [comment]
I'll have a look at removal - it should work, but maybe I need to update something there.  On the sound modes, open a new PR when you get a chance, and I'll let you know what I need in there.  I'll close this one now.

Fixed in 1.62

**Comment by peteS-UK** [comment]
Fix in 1.62

**Comment by peteS-UK** [comment]
@JoshMcWilson, I've fixed the issue of deleting existing extra notifications - the way the configure flow works is a bit odd.  I also have a fix for the new warning they just added on background tasks.  I'll post these fixes as part of a new version if we can get the sound modes sorted out.
